CREATE DATABASE n07_08;
USE n07_08;

	CREATE TABLE students (
		student_code INT AUTO_INCREMENT PRIMARY KEY,
		full_name VARCHAR(50) NOT NULL,
		email VARCHAR(100) NOT NULL UNIQUE,
		age INT NOT NULL
	);